AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TrustedPrincipal:
    Type: String
    Description: ARN allowed to assume the role

  KeyAdminArn:
    Type: String
    Description: ARN of IAM user/role that can administer this key
    
  LambdaCodeBucketName:
    Type: String
    Description: Name of S3 bucket containing the Lambda function code
    Default: "pqc-code-bucket"
  
  LambdaCodeVersion:
    Type: String
    Description: S3 Object Version of the Lambda function code zip file
    Default: "latest"
  
  LambdaMemorySize:
    Type: Number
    Description: Memory size for the Lambda function in MB
    Default: 1024

Resources:
  KeyUsageRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref TrustedPrincipal
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: AllowUseOfMldsA44Key
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: "*"

  KmsLatencyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: AllowLogsAndKmsSignVerify
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - kms:Sign
                  - kms:Verify
                  - kms:GetPublicKey
                  - kms:DescribeKey
                Resource: 
                  - "*"

  KmsLatencyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: "nodejs22.x"
      Handler: "app.handler"
      Role: !GetAtt KmsLatencyFunctionRole.Arn
      Timeout: 900
      MemorySize: !Ref LambdaMemorySize
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: "test-aws-kms-latency/function.zip"
        S3ObjectVersion: !Ref LambdaCodeVersion
      Environment:
        Variables:
          ML_DSA_44_ARN: !GetAtt MLDSA44Key.Arn
          ML_DSA_65_ARN: !GetAtt MLDSA65Key.Arn
          ML_DSA_87_ARN: !GetAtt MLDSA87Key.Arn
          ECC_NIST_P256_ARN: !GetAtt ECCP256Key.Arn
          ITERATIONS: "500"
          USE_PARALLEL: "true"
  
  InvokeFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: "NONE"
      TargetFunctionArn: !GetAtt KmsLatencyFunction.Arn

  InvokeFunctionUrlPermissionPublic:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KmsLatencyFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  InvokeFunctionPermissionPublic:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KmsLatencyFunction
      Action: lambda:InvokeFunction
      Principal: "*"


  MLDSA44Key:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      EnableKeyRotation: false
      PendingWindowInDays: 7
      KeySpec: "ML_DSA_44"
      KeyUsage: "SIGN_VERIFY"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowKeyAdmin
            Effect: Allow
            Principal:
              AWS: !Ref KeyAdminArn
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowRoleUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KeyUsageRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

          - Sid: AllowLambdaUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KmsLatencyFunctionRole.Arn
            Action:
              - kms:Sign
              - kms:Verify
              - kms:GetPublicKey
              - kms:DescribeKey
            Resource: "*"

  MLDSA65Key:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      EnableKeyRotation: false
      PendingWindowInDays: 7
      KeySpec: "ML_DSA_65"
      KeyUsage: "SIGN_VERIFY"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowKeyAdmin
            Effect: Allow
            Principal:
              AWS: !Ref KeyAdminArn
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowRoleUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KeyUsageRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

          - Sid: AllowLambdaUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KmsLatencyFunctionRole.Arn
            Action:
              - kms:Sign
              - kms:Verify
              - kms:GetPublicKey
              - kms:DescribeKey
            Resource: "*"

  MLDSA87Key:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      EnableKeyRotation: false
      PendingWindowInDays: 7
      KeySpec: "ML_DSA_87"
      KeyUsage: "SIGN_VERIFY"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowKeyAdmin
            Effect: Allow
            Principal:
              AWS: !Ref KeyAdminArn
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowRoleUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KeyUsageRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

          - Sid: AllowLambdaUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KmsLatencyFunctionRole.Arn
            Action:
              - kms:Sign
              - kms:Verify
              - kms:GetPublicKey
              - kms:DescribeKey
            Resource: "*"

  ECCP256Key:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      EnableKeyRotation: false
      PendingWindowInDays: 7
      KeySpec: "ECC_NIST_P256"
      KeyUsage: "SIGN_VERIFY"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowKeyAdmin
            Effect: Allow
            Principal:
              AWS: !Ref KeyAdminArn
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowRoleUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KeyUsageRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

          - Sid: AllowLambdaUse
            Effect: Allow
            Principal:
              AWS: !GetAtt KmsLatencyFunctionRole.Arn
            Action:
              - kms:Sign
              - kms:Verify
              - kms:GetPublicKey
              - kms:DescribeKey
            Resource: "*"

Outputs:
  FunctionUrl:
    Value: !GetAtt InvokeFunctionUrl.FunctionUrl